version: '3'
services:
  main:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - counter
  counter:
    build:
      context: ./counter
      dockerfile: Dockerfile
    ports:
      - 3001:3001
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
